name: Continuous Integration

on: [push, pull_request]

jobs:
  client-build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Client Dependencies
        run: |
          cd packages/client
          npm install
        env:
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

      - name: Run lint
        run: cd packages/client && npm run lint

      - name: Build Client
        run: cd packages/client && npm run build
        env:
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: packages/client/dist
          key: ${{ runner.os }}-client-build-${{ github.sha }}

  shared-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Shared Dependencies
        run: cd packages/shared && npm install

      - name: Build Shared Package
        run: cd packages/shared && npm run build

      - name: Cache Shared Build
        uses: actions/cache@v3
        with:
          path: packages/shared/dist
          key: ${{ runner.os }}-shared-build-${{ github.sha }}

  server-setup:
    needs: [client-build-and-lint, shared-build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: packages/client/dist
          key: ${{ runner.os }}-client-build-${{ github.sha }}

      - name: Restore shared build
        uses: actions/cache@v3
        with:
          path: packages/shared/dist
          key: ${{ runner.os }}-shared-build-${{ github.sha }}

      - name: Install Dependencies and Link Shared
        run: |
          # Install shared package
          cd packages/shared
          npm install
          npm run build
          npm link

          # Install server package and link to shared
          cd ../server
          npm install --ignore-scripts
          npm link @polylink/shared

      - name: Run lint
        run: cd packages/server && npm run lint

      - name: Build Server
        run: cd packages/server && npm run build

    # Placeholder for future server-side testing
    # - name: Run Server Tests
    #   run: cd server && npm test
