name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      # Install dependencies for both Client and Server
      - name: Install Dependencies
        run: |
          npm run install:all

      # Build Client
      - name: Build Client
        run: |
          npm run build --prefix Client

      # No build step for server, assuming server is already ready to run and just needs npm install

      - name: Zip Client and Server for deployment
        run: |
          zip -r release.zip Client/ server/ -x "Client/node_modules/*" "server/node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: full-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-package
    environment:
      name: "Production"
      url: ${{ steps.deploy_to_webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: full-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_793C190B6BA943E1B79D428040C92511 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AC741A1B6274C378DF1110AE3ECB3EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_429425FACD5A4334875D6D975D40BC01 }}

      - name: Deploy to Azure Web App
        id: deploy_to_webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "laep-llm"
          package: .
