name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install dependencies which also triggers the client build via the postinstall script
      - name: Install Dependencies and Build Client
        run: npm run install:all

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_793C190B6BA943E1B79D428040C92511 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AC741A1B6274C378DF1110AE3ECB3EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_429425FACD5A4334875D6D975D40BC01 }}

      - name: Deploy to Azure Web App
        id: deploy_to_webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "laep-llm"
          package: .
